---
number-depth: 2
---

# Getting Started

## Important Links

**Course Link:** <a href="https://seek.onlinedegree.iitm.ac.in/courses/ns_25t2_cs1902" target="_blank">Check the course portal</a> <br>
**Course Calendar:** <a href="https://calendar.google.com/calendar/u/2?cid=Y19uMDJwamZ1YzZ2bnF2a2FtYjM2M2Jsbms5OEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t" target="_blank">Calendar for this course</a> <br>
**Lab Meeting Link:** <a href="https://meet.google.com/jbe-xuew-hia" target="_blank">https://meet.google.com/jbe-xuew-hia</a> <br>

**Tutorial Videos to get started:** <br>

- <a href="https://youtu.be/sSxoWkmOoMk" target="_blank">VM Login process explained in step by step</a> <br>
- <a href="https://youtu.be/UDaSLK4QtZQ" target="_blank">To use course VM and solve assignments</a>

## VM-Access

1. Open your terminal/command prompt/powershell from your system (**NOT from the VirtualBox**)

2. For simpler setup do not enter any passphrase and skip all the prompts by pressing Enter

3. Type `ssh-keygen` in the terminal/command prompt/powershell and Enter. You should see output similar to the following:

```bash
<username>@my-laptop:~$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/<username>/.ssh/id_rsa):
Created directory '/home/<username>/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/<username>/.ssh/id_rsa
Your public key has been saved in /home/<username>/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:MyMwAvTo90BeuaGhaS9aq3Lc2QivijK7oMkigMCm14Y <username>@my-laptop
The key's randomart image is:
+---[RSA 3072]----+
|o.               |
| .o   .          |
|...+o+           |
|oo=.+oo          |
|== B .. S        |
|= E =  . +       |
|o+.* =           |
|%o+.= .          |
|#Oo.             |
+----[SHA256]-----+
```

4. By default, if the file is not specified

- Public key will be stored as `~/.ssh/id_ed25519.pub` or `C:\Users\<username>\.ssh\id_rsa.pub`.
- Private key will be stored as `~/.ssh/id_ed25519` or `C:\Users\<username>\.ssh\id_rsa`

5. To view the public key, use `cat` command to display the content of the public key which ends with `.pub` inside the `~/.ssh` directory (by default) (For Windows follow the above directory structure)

```bash
cat ~/.ssh/id_rsa.pub (or)
cat ~/.ssh/id_ed25519.pub 
```

6. Copy and paste the content of the public key (NOT THE PRIVATE KEY) that ends with `.pub` into the "SSH Key" form field on the <a target='_blank' href='https://cs1102.study.iitm.ac.in'>website</a> (use your student email ID to log in).

7. After submitting the SSH key, you can log in to the VM using SSH from your system.

- Ensure the directory ~/.ssh with file permission 700
- Ensure the files ~/.ssh/id_rsa.pub and ~/.ssh/id_rsa with file permission 600.

8. The following command used to connect remote machine via SSH using the default private key (`~/.ssh/id_rsa` or `~/.ssh/id_ed25519`)

```bash
ssh <roll-number>@cs1102.study.iitm.ac.in
```

9. The below command used to connect remote machine via SSH using the custom private key path

```bash
ssh -i <path/to/private/key> <roll-number>@cs1102.study.iitm.ac.in
```

10. Once, you have logged in your command prompt will look like:

<div style="background-color:white">
<span style="color: green;">\<roll-number\>@cs1102</span>:<span style="color: blue;">~</span>$
</div>

::: {.callout-note}
Read more about SSH by clicking <a href="https://docs.google.com/presentation/d/1SkmbBeWBzONkF5ZiChgglqE0L4koH_JXJtYQ2oGeTGY/view" target="_blank">here</a>
:::