---
number-depth: 2
---

# Lab-5

**Week-9:** <a href="https://youtu.be/k3q-9ntZI4s" target="_blank">AWK Programming Part 1</a>,
<a href="https://youtu.be/g9_ij64u8eQ" target="_blank">AWK Programming Part 2</a><br>

**Week-10:** <a href="https://youtu.be/tzYx6DKtvGw" target="_blank">Version Control - Part 01</a>,
<a href="https://youtu.be/B9XVOO9ERis" target="_blank">Version Control - Part 02</a>,
<a href="https://youtu.be/pbb5YQQhqXU" target="_blank">Knowing your Hardware</a>,
<a href="https://youtu.be/UBjENhxwpcU" target="_blank">Prompt String</a>,
<a href="https://youtu.be/BvAtNUX7da4" target="_blank">Managing Storage</a>

:::{.callout-note}
Do not repeat examples from the lab session in your report, as they are intended to guide your understanding
:::

:::{.callout-tip appearance="simple"}
All the necessary files for the lab questions can be found in the `/opt/lab_assets` directory in the course VM
:::

## AWK Scripting

**Q1:** Determine the number of students who passed each course from the file `student_grades.csv`. **(7 marks)**

**Q2:** Calculate the average score of students in the Computer Science subject whose names start with the letter 'A'. The script should accept gender as a variable while processing the file `random_student_data.csv`. **(7 marks)**

**Q3:** Extract the date from the timestamp and store it in an array. Compute the total sales amount for each day and the monthly total sales from the file `sales_data.csv`. **(7 marks)**

**Q4:** Write an AWK script to compute the average total power consumption (in GWh) for each state and determine the state with the highest total power consumption from the file `state_power_supply.csv`. **(7 marks)**

**Q5:** Calculate the total power consumption in the last five years (from the current year) for the state of New York using data from the file `state_power_supply.csv`. **(7 marks)**

**Q6:** Define an AWK function to check whether a number is prime. Store all prime chemistry subject marks and compute the median from the file `random_student_data.csv`. **(7 marks)**

**Q7:** Given a file `corr.json`, extract the fields `A` and `B`, store them in a CSV file, and write an AWK script to compute the covariance between the two columns. **(8 marks)**

**Formula for Covariance**
$$
\text{Cov}(A, B) = \frac{\sum_{i=1}^{n} (A_i - \bar{A}) (B_i - \bar{B})}{n}
$$

:::{.callout-warning icon="false" appearance="minimal"}
**Hint:** Use `jq` command to `json` to `csv` and you can use multiple awk script files as well
:::

## Git Version Control

<p style="font-size:18px">**Q8 GitHub Repository** **(10 marks)**</p>

- **Q8.1:** Create a new public repository named `<your-roll-number>-cs1102-linux-lab` on GitHub. Enable Two-Factor Authentication (2FA) and generate a personal access token. 
- **Q8.2:** Clone the repository and initialize Git in your local directory. 
- **Q8.3:** Set your GitHub username and email in the `.gitconfig` file in your home directory.
- **Q8.4:** Check the repository status, add the file to staging, commit the changes, and push them to GitHub.
- **Q8.5:** Create a `README.md` file and add your personal bio. 
- **Q8.6:** Enable GitHub Pages for your repository and publish `README.md` file as site. 

<p style="font-size:18px">**Q9 Branches and Commits** **(10 marks)**</p> 

- **Q9.1:** Create a new branch, switch to it, and update the `README.md` file. 
- **Q9.2:** Add, commit, and push changes to the branch.
- **Q9.3:** Merge the new branch with the main branch.
- **Q9.4:** Push the new changes to the branch.
- **Q9.5:** Check the commit history using the command line. 
- **Q9.6:** Revert the most recent commit.

:::{.callout-note appearance="simple"}
Feel free to explore the other commands like `git pull`, `git stash`, `git blame`, `git reset`
:::

## User and Group Management 

:::{.callout icon="false"}
Perform this task in your local machine and refer to the [instructions](/lab_instructions.qmd) 
:::

**(10 marks)**

- **Q10.1:** Create a new user with a home directory. 
- **Q10.2:** Create a new group and assign the user to it. 
- **Q10.3:** Create a new file in the user's home directory and change the groups for that file to newly created group. (Make sure the group has enough permission to access the file) 


## SSH Setup 

:::{.callout icon="false"}
Perform this task in your local machine and refer to the [instructions](/lab_instructions.qmd) 
:::

**(20 marks)**

- **Q11.1:** Add an SSH key for the new user and change ownership and group of the `.ssh` directory.
- **Q11.2:** Start the OpenSSH server.
- **Q11.3:** Log into the newly created user’s shell via SSH `ssh <username>@<ip-address>` through cmd prompt or powershell (if your using Linux or Mac, you can use the same terminal). 
- **Q11.4:** Grant the new user sudo privileges. 
- **Q11.5:** Remove the sudo user privileges. 
- **Q11.6:** Delete the user and group.
- **Q11.7:** Stop the OpenSSH server. 