---
number-depth: 2
---

# Lab-2

**Week-3:** <a href="https://youtu.be/Lcx9UsS7y8Y" target="_blank">Combining commands and files</a>, 
<a href="https://youtu.be/BBh69kH_G_Y" target="_blank">Redirections</a>, 
<a href="https://youtu.be/OAEVYgH1IMM" target="_blank">Software Management - Part 01</a>, 
<a href="https://youtu.be/3saraSGT1i0" target="_blank">Software Management - Part 02</a>, 
<a href="https://youtu.be/2aThmDRvSWU" target="_blank">Linux process management</a><br>

**Week-4:** <a href="https://youtu.be/1y85iTaqq8Y" target="_blank">Pattern Matching - Part 01</a>, 
<a href="https://youtu.be/XQUJPRc-7zA" target="_blank">Pattern Matching - Part 02</a>

:::{.callout-note}
Do not repeat examples from the lab session in your report, as they are intended to guide your understanding
:::

:::{.callout-tip appearance="simple"}
All the necessary files for the lab questions can be found in the `/opt/lab_assets` directory in the course VM
:::


## Combining Commands and Redirections

**Q1:** Check whether the last command (it could be any command) executes successfully or not, if it executes successfully print `SUCCESS` else `FAIL`. The output should be only `SUCCESS` or `FAIL` in the terminal. **(4 marks)**

::: {.callout-warning icon="false" appearance="minimal"}
**Hint:** Use Redirections
:::

**Q2:** Write a command that accepts input in the terminal until you type `SENTENCE COMPLETED`. **(4 marks)**

**Q3:** There is log file named "`worklog.log`" where every employee has to update their daily worklog in this file. The file already contains some logs in it. Your task is write your daily worklog file named `log_<date>.txt` in the `worklog.log` file. If there are any errors during the process, they should be redirected to the `error.log` file. **(4 marks)**

**Q4:** There are multiple files in the `/lab_assets` directory. Your task is collect all the **txt** files (which are in `.txt` format) and combine them into a single file named `combined_files.txt`. **(4 marks)**


**Q5:** The file named `passwords.txt` contains the list of passwords. You are required to mask all the special characters with the `*` characters and redirect the output to `masked_passwds.txt`. **(4 marks)**

::: {.callout-warning icon="false" appearance="minimal"}
**Hint:** Use `tr` command
:::

```js
# Sample Input
---
ghUh;15%
qew*3r"5
1fcDo)$.
~e45*hmn
```

```js
# Sample Output
---
ghUh*15*
qew*3r*5
1fcDo***
*e45*hmn
```


**Q6:** You are a regular user who logs into multiple websites daily(site and user_id is in the file `user_ids.txt`) but finds it difficult to remember all the passwords. Write a script that generates a random password of length 8 and stores it in a file named `gen_passwd.txt`. **(Bonus)**

```js
# Sample Input file 
#,Website,Username
-----
1,Gmail,25f1234567@es.study.iitm.ac.in
2,Facebook,25f1234567@es.study.iitm.ac.in
3,Instagram,25f1234567
4,LinkedIn,25f1234567
```

```js
# Sample Output file
#,Website,Username,Password
-----
1,Gmail,25f1234567@es.study.iitm.ac.in,ghUh;15%
2,Facebook,25f1234567@es.study.iitm.ac.in,qew*3r"5
3,Instagram,25f1234567,1fcDo)$.
4,LinkedIn,25f1234567,~e45*hmn
```

::: {.callout-tip}
Explore the commands `basenc` `/dev/random` `/dev/urandom` `cut` `head` `paste` using `man`
::: 

## Software Management  

**Q7:** Mention at least **five** command-line utilities or software tools that you find useful. *(Conduct some research on GitHub and other sources.)*  **(15 marks)**


:::{.callout icon="false"}
Perform this task in your local machine and refer to the [instructions](/lab_instructions.qmd) 

If a tool has multiple features, demonstrate **at least three** use cases. *(This will be counted as one command-line utility.)*  
:::

###### **Example:**

```bash
ffmpeg -i input.mkv output.mp3 # Convert video to audio
ffmpeg -i input.mp4 -q:a 0 -map a output.mp3 # Extract audio from a video
ffmpeg -f concat -i file_list.txt -c copy output.mkv # Concatenate multiple video or audio files
ffmpeg -i input.mp4 -vf subtitles=my_subtitles.srt output.mp4 # Burn subtitles into a video
ffmpeg -i input.mp4 -i watermark.png -filter_complex "overlay=10:10" output.mp4 # Add an image or text watermark to a video
ffmpeg -i SourceFileName.mkv -c:a copy -c:v copy -ss hh:mm:ss.xxx -to hh:mm:ss.xxx OutputFileName.mkv # Trim or cut parts of a video
# ...
```

<center> 
-------------------------**OR**-------------------------
</center>

:::{.callout icon="false"}
If a tool has only **one primary use**, you must demonstrate **at least three** different tools. *(This will be counted as one command-line utility.)* 
:::

###### **Example:**

```bash
dict empathy  # 'dict' is primarily used as a dictionary
factor 10  # 'factor' is mainly used to print the prime factors of a number
echo hello | rev  # 'rev' is primarily used to reverse a string
```

## System Services and Processes Management in Linux

**Q8.1:** Execute the `top | head -7` command. What information does the `top | head -7` command provides you and explain the terms & info in it thoroughly? **(4 marks)**

**Q8.2:** Display the top 10 CPU-consuming processes. **(2 marks)** 

```js
In the format: 
PID %CPU COMMAND
```

**Q8.3:** Display the top 10 processes consuming the most memory. **(2 marks)**

```js
In the format: 
PID %MEM COMMAND
```


**Q9:** Your Device is control hub. Learn how to control the control hub! **(8 marks)**

:::{.callout}
Perform this task in your local machine and refer to the [instructions](/lab_instructions.qmd)
:::
Controlling Bluetooth Devices using `bluetoothctl`:

- Scan and list available Bluetooth devices.
- Pair with a device and establish a connection.
- Disconnect and remove the paired device.  
- Along the way, explain key terms and information you have used and found.


## Pattern Matching

**Q10:** List all the script files (`.sh`, `.sed`, `.awk`) inside the `/opt/cs1102` directory, including those in subdirectories. Also, count the number of `.sed` and `.awk` files. **(7 marks)**

**Q11:** Check the given word is palindrome or not, if it is palindrome print `"PALINDROME"` else `"NOT PALINDROME"`. **(3 marks)**

```js
# Sample Input
-----
MALAYALAM
```

```js
# Sample Output
-----
PALINDROME
```

**Q12:** Count the number of students who passed the Linux course (those who received grades S, A, B, C, D, or E) in the Jan 2025 term (F1-2025) **(6 marks)**

```js
# Sample Input
---
roll_no, course_code, course_name, term-code, grade
27f7034476, CS1002,CS1002 - Embedded C Programming, F3-2026, WQ
27f1877386, CS1002,CS1002 - Embedded C Programming, F2-2025, U
27f6600140, CS2001,CS2001 - Python Programming, F2-2025, A
29f7986047, CS2001,CS2001 - Python Programming, F2-2026, WQ
26f6674179, CS1001,CS1001 - C Programming, F3-2025, E
27f3111167, CS2001,CS2001 - Python Programming, F3-2025, U
26f1556539, CS1102,CS1102 - Linux Shell, F1-2025, A
```

```js
# Sample Output 
-----
1
```

**Q13:** Extract all lines that contain more than one occurrence of the input word `rain` in a file named `small_corpus.txt`. **(4 marks)**

**Q14:** You are working in some financial sector and your manager has given task to extract the unique PAN number. We have given the file named `random_pan_aadhaar.txt` which includes details of PAN card number in the txt file. **(3 marks)**

```js
# Sample Output
-----
ABCDE1234F
QWERT5678Y
```

**Q15:** In continuation to Q14th question, the manager has given the same file named `random_pan_aadhaar.txt` but he is unsure whether it has Aadhaar number or PAN number (case insensitive). So you are required match both PAN and Aadhaar number. **(7 marks)**

```js
# Sample Output
-----
ABCDE1234F
QwErT5678y
1234 4567 6789
1234-4567-6789
```

**Q16:** Display the lines that are common to both files. You can either use existing files or create your own for this task. **(4 marks)**

:::{.callout-warning icon="false" appearance="minimal"}
**Hint:** Use `diff` command
:::

**Q17:** Write a script to extract all usernames with valid passwords from the file (use the output file `gen_passwd.txt` from Q6 in the "Combining commands and redirections" section) **(Bonus)**


```js
**Criteria for valid password:**

- A password should contain atleast 1 upper char
- A password should contain atleast 1 lower char
- A password should contain atleast 1 digit
- A password should contain atleast 1 special char
- A password should have a length of atleast 8 characters
```


```js
# Sample Output
-----
1,Gmail,25f1234567@es.study.iitm.ac.in,ghUh;15%
3,Instagram,25f1234567,1fcDo)$.
```

## Text Editors + Regex

**Q18:** Log in to the VM and navigate to `/opt/cs1102/lab_assets/NPTEL`. Locate an HTML file with your roll number, copy it to your home directory, and extract only video links from this file using `vi` or `emacs` (Take Screenshot for each operation highlighting bottom of the screen). **(15 marks)**

:::{.callout-warning icon="false" appearance="minimal"}
**Hint:** Refer to this <a href="https://discourse.onlinedegree.iitm.ac.in/t/power-of-linux/144867" target="_blank">discourse post</a>
:::

:::{.callout-note}
This question highlights that no one can know or learn everything. However, most problems already have solutions available on platforms like StackOverflow, AskUbuntu, and other forums. In the digital age, it’s essential to cultivate the habit of searching for solutions and learning new concepts from such resources.
:::